### ISSUE TITLE
Score and Tournament Tracking

### ISSUE THREAD

**Issue by dimitar-st-atanasov** [Final-project-of-Team-5-Telerik-Academy/final_project_team_5#11]
- [ ] Information is available without any authentication (**must**);

- [ ] View any past, present or future tournament (**must**);

- [ ] View any match (**must**);

- [ ] View any player profile (**should**):

   - Tournaments played / won (**should**);

   - Matches played / won (**should**);

   - Most often played opponent (**should**);

   - Best opponent – win/loss ratio (**should**);

   - Worst opponent – win/loss ratio (**should**);
